import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
import { Montserrat } from 'next/font/google';

const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap', // Ensures a fallback font is displayed while Montserrat loads
  weight: ['400', '700'], // Specify the weights you need (optional, loads all by default)
  variable: '--font-montserrat', // Define a CSS variable (optional, useful for Tailwind CSS)
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={montserrat.className}>

        {children}
      </body>
    </html>
  );
}
